// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS6ighKd0sQ1KjF8hfexv-ElKdnANIkn0',
    appId: '1:8666073820:web:ada6625951bc0a4d114219',
    messagingSenderId: '8666073820',
    projectId: 'iti-training-3adfa',
    authDomain: 'iti-training-3adfa.firebaseapp.com',
    storageBucket: 'iti-training-3adfa.appspot.com',
    measurementId: 'G-BS4BCTR68J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjSjTrFXjvK5KPY0QKc3rTGURgyvUW1v0',
    appId: '1:8666073820:android:65a0bb37f70d7c05114219',
    messagingSenderId: '8666073820',
    projectId: 'iti-training-3adfa',
    storageBucket: 'iti-training-3adfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoyWLeqRrNQjN7RjGgLzUEKuSFxbw5Iaw',
    appId: '1:8666073820:ios:ec8891fcf364b6d8114219',
    messagingSenderId: '8666073820',
    projectId: 'iti-training-3adfa',
    storageBucket: 'iti-training-3adfa.appspot.com',
    iosClientId: '8666073820-n954m53i6fh8mhu3f79dij4561hc3a7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoyWLeqRrNQjN7RjGgLzUEKuSFxbw5Iaw',
    appId: '1:8666073820:ios:ec8891fcf364b6d8114219',
    messagingSenderId: '8666073820',
    projectId: 'iti-training-3adfa',
    storageBucket: 'iti-training-3adfa.appspot.com',
    iosClientId: '8666073820-n954m53i6fh8mhu3f79dij4561hc3a7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLab2',
  );
}
